HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'}
URL_MOVIEMETER="https://www.imdb.com/chart/moviemeter/"
URL_TVMETER="https://www.imdb.com/chart/tvmeter/"
FILM_PROPERTIES=["name", "genre", "url", "description"]
AGGREGATE_RATING=["ratingValue", "ratingCount", "bestRating", "worstRating"]
BASE_URL="https://www.imdb.com"
ACTOR_NAME_CLASS="sc-cd7dc4b7-1 kVdWAO"
DATE_OF_BIRTH="sc-59a43f1c-2 bMLVWg"
ACTOR_PREVIOUS_FILMOGRAPHY="ipc-metadata-list-summary-item__t"
SPAN_RATING="ipc-rating-star--rating"
TOP_LIMIT=5